### ISSUE TITLE
Include keywords in table so they affect the search

### ISSUE THREAD

**Issue by thlorenz** [eirikb/nipster#10]
Currently only title and description are considered.

Lots of packages take great care to define proper keywords and most other searches (i.e. `npm search` and [node-package-finder](http://packagefinder1-enome.dotcloud.com/)) take these into account.

**Comment by eirikb** [comment]
I just added a hidden column, and added each keyword as space. Hope this is how you meant it.
You can see it in action with express at top when searching for [restful](http://eirikb.github.com/nipster/#restful).

**Comment by thlorenz** [comment]
NIce, that is exactly how I thought it could be added - no one wants to see the keywords anyways ;)

Just tried it and it works as expected, thanks!

**Comment by eirikb** [comment]
Added keywords as title to the npm-link, just in case :smile:
