### ISSUE TITLE
Debounce the search

### ISSUE THREAD

**Issue by thlorenz** [eirikb/nipster#11]
In order for this to be a nicer UI experience and not slow down inputting chars, nipster should debounce the filtering.
I.e. only do it once the user paused typing for 200ms or so.

Right now it filters immediately on every keystroke, causing four unnecessary searches for `a`, `as`, `asy`, `asyn` when all I wanted to see was `async`.

**Comment by eirikb** [comment]
This commit: https://github.com/eirikb/nipster/commit/4d379d4af0020103f8a84bfaa84f3722a301a8e1 should fix this.
I actually had to add the plugin http://www.datatables.net/plug-ins/api#fnSetFilteringDelay manually, can't imagine that is best practice. But at least it should work now.
