### ISSUE TITLE
many invalid packages

### ISSUE THREAD

**Issue by DTrejo** [eirikb/nipster#12]
http://eirikb.github.io/nipster/#readme

Hey, if you go to page 2 and on of this search, you will see many invalid packages.

Would be great if those were excluded by nipster, as they do not even have a `name` field.

http://eirikb.github.io/nipster/#readme

Cheers and thanks!
D

**Comment by eirikb** [comment]
I think this is really me doing something stupid, now it should show package names for packages without github links. Although there does seem to be a lot of packages on version 0.0.1 with that description which where updated recently.
