### ISSUE TITLE
please put this on a domain

### ISSUE THREAD

**Issue by timoxley** [eirikb/nipster#16]
any domain… just something that's easier to remember/type. I have to google for this every time.

**Comment by eirikb** [comment]
You know about nipster.eirikb.no, it's just a silly redirect but perhaps it helps?

**Comment by timoxley** [comment]
did not know, but still kinda wordy.

**Comment by eirikb** [comment]
Yeah agreed. Suggestions for domain name? I don't want to waste a lot of money on one, so something like .com would be great.  I see nipster.io is available, but that would be the opposite of cheap.

**Comment by eirikb** [comment]
Ok so I found out nipstr was available, and bought nipstr.com and set it up now, so http://nipstr.com/ should work.  
Should I change the project name as well? I really don't see that I must. Comments?

**Comment by timoxley** [comment]
great!

github gives you a redirect I believe, so it shouldn't have any negative impact, nice to keep things consistent.

**Comment by dandv** [comment]
:+1: for updating the URL in the GitHub repo.

**Comment by DTrejo** [comment]
+1 nice work

**Comment by DTrejo** [comment]
Great job :) loving it :)
