### ISSUE TITLE
please url-encode the #hash%20value ?

### ISSUE THREAD

**Issue by DTrejo** [eirikb/nipster#7]
Would be great if this could be added, as then I'd be able to make links to certain searches.

Relevant line: https://github.com/eirikb/nipster/blob/gh-pages/main.js#L43

Would you be open to a pull request for this?

Thank you,
D

**Comment by eirikb** [comment]
Do you think a normal encodeURIComponent would be enough?

**Comment by DTrejo** [comment]
Yes! I think that would be perfect! :)
On Jul 10, 2012 11:13 PM, "Eirik Brandtzæg" <
reply@reply.github.com>
wrote:

**Comment by DTrejo** [comment]
(And decodeuricomponent as well)

**Comment by eirikb** [comment]
It seems History.js decodes the string, so a simple `window.History.replaceState({}, '', '#' + encodedInput)` will not work. But I also noticed that History.js actually does not support hashes, so we might have to revert back to a normal change. Reverting will break the back-button-fix which History.js provides. I guess a quick workaround is to just check if window.history exists and use it when possible, as little functionality is actually used.

**Comment by DTrejo** [comment]
Thanks for looking into this. You can now see that the node.js irc chatroom has the bot running.

To see you site in action:

```
npm search nipster
```

and a problem-child search:

```
npm search nipster rocks
> http://eirikb.github.com/nipster/#nipster%20rocks
```

**Comment by eirikb** [comment]
I see the problem now, so I made a quick fix for this.  
Looks good? http://eirikb.github.com/nipster/#nipster%20rocks

**Comment by DTrejo** [comment]
SCORE!

Thank your Eirik!
D
