### ISSUE TITLE
additional sorting

### ISSUE THREAD

**Issue by mscdex** [eirikb/nipster#8]
How about being able to sort packages by created and last updated date/times?

**Comment by eirikb** [comment]
Sounds interesting. Current nipster use http://registry.npmjs.org/-/all and I can see a _time.modified_ property making it possible to fetch date of change to latest version. To get the initial date we need to either fetch each package and look at the date of first version mentioned (I guess), or look at when the github repository was created. A bit resource heavy perhaps?

**Comment by mscdex** [comment]
Just having last modified is fine.
